modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
[[mods]]
modId="speakermod"
version="${file.jarVersion}"
displayName="SpeakerMod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wireless-speakers"
updateJSONURL="https://github.com/mactso/SpeakerMod/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Speaker Mod.'
[[dependencies.speakermod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.speakermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="SERVER"
